import { QdrantClient } from '@qdrant/js-client-rest';
import dotenv from 'dotenv';

dotenv.config();

const qdrantClient = new QdrantClient({
  url: process.env.QUADRANT_CLUSTER_ENDPOINT,
  apiKey: process.env.QUADRANT_API_KEY,
});



// Initialize Framework Collection
const initFrameworkCollection = async () => {
  const collectionName = "frameworks";
  try {
    const res = await qdrantClient.getCollections();
    const exists = res.collections.some(c => c.name === collectionName);
    
    if (!exists) {
      await qdrantClient.createCollection(collectionName, {
        vectors: {
          size: 384, // The vector size generated by our Hugging Face model
          distance: "Cosine", // Standard distance metric for text embeddings
        },
      });
      // Create a payload index so we can filter by frameworkId
      await qdrantClient.createPayloadIndex(collectionName, {
        field_name: "frameworkId",
        field_schema: "keyword",
      });
      console.log(`✅ Qdrant Collection '${collectionName}' created successfully.`);
    } else {
      console.log(`ℹ️ Qdrant Collection '${collectionName}' already exists.`);
    }
  } catch (err) {
    console.error(`❌ Error setting up Qdrant Collection '${collectionName}':`, err);
  }
};

// Test connection and initialize
try {
  const res = await qdrantClient.getCollections();
  console.log("✅ Qdrant Database Connected:", res.collections.length, "collections found.");
  // Create collection if it doesn't exist
  await initFrameworkCollection();
} catch (err) {
  console.error("❌ Qdrant Database Connection Error:", err);
}

export default qdrantClient;
